Add algorithm includes
Add algorithm includes to fix C++23 build errors because C++23 removed

certain transitive includes

Error:

hardware/nxp/weaver/test_kill_secureelement/weaver_kill_secureelement_test.cpp:65:38:

error: no member named 'all_of' in namespace 'std'; did you mean

'__all_of'?

   65 |         if (!pid_str.empty() && std::all_of(pid_str.begin(),

pid_str.end(), ::isdigit)) {

Flag: EXEMPT PURE_REFACTOR

Bug: 429048222

Test: m weaver_kill_secureelement_test